### ISSUE TITLE
no such table: marketplace_volunteerprofile

### ISSUE THREAD

**Issue by darenasc** [dssg/marketplace#24]
Hi, I can build the Docker image but got the following error, after starting the container. It can't find the table `marketplace_volunteerprofile`.

From the `docker logs` I got the following extract when the container is created.
```
[2018-12-04 00:05:33 +0000] [15] [INFO] Booting worker with pid: 15
[2018-12-04 00:05:33 +0000] [9] [DEBUG] 4 workers
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2018-12-04 00:05:34,032 INFO success: webapp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[03/Dec/2018 18:05:40] ERROR [django.request:118] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: marketplace_volunteerprofile
```
And from the browser the following extract:
```
Traceback:

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  303.         return Database.Cursor.execute(self, query, params)

The above exception (no such table: marketplace_volunteerprofile) was the direct cause of the following exception:

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/app/marketplace/views/user.py" in home_view
  200.     featured_volunteer = UserService.get_featured_volunteer()

File "/app/marketplace/domain/user.py" in get_featured_volunteer
  252.             .order_by('-average_review_score', '-taskcount') \

File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py" in first
  607.         for obj in (self if self.ordered else self.order_by('pk'))[:1]:

File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py" in __iter__
  272.         self._fetch_all()

File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py" in _fetch_all
  1182.             self._result_cache = list(self._iterable_class(self))

File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py" in __iter__
  53.         results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1068.             cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/utils.py" in __exit__
  89.                 raise dj_exc_value.with_traceback(traceback) from exc_value

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  303.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /
Exception Value: no such table: marketplace_volunteerprofile
```

What this could be? thank you.

**Comment by jesteria** [comment]
It appears that your database was never migrated, and as such the application's tables were never created.

[The README](https://github.com/dssg/marketplace#local-app-intialization) might help?

Feel free to reopen this issue if that's not the case.
